apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-checkout
spec:
  inputs:
    parameters:
      - name: gh-repo
      - name: template-dir
  script:
    image: alpine/git
    command: [ "/bin/sh", "-c" ]
    volumeMounts:
      - name: workspace
        mountPath: /workspace
    env:
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-token
            key: token
      - name: GH_REPO
        value: "{{ "{{inputs.parameters.gh-repo}}" }}"
      - name: TEMPLATE_DIR
        value: "{{ "{{inputs.parameters.template-dir}}" }}"
    args:
      - >
        git clone --single-branch -b main https://x-access-token:$GIT_TOKEN@github.com/$GH_REPO.git $TEMPLATE_DIR;
        echo 'Repository cloned successfully';
